In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from xml.etree import ElementTree
from config import z_key

# MTA info

In [2]:
mta_data = pd.read_csv('http://web.mta.info/developers/data/nyct/subway/Stations.csv')
mta_data.head()

,Station ID,Complex ID,GTFS Stop ID,Division,Line,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude
0,1,1,R01,BMT,Astoria,Astoria - Ditmars Blvd,Q,N W,Elevated,40.775036,-73.912034
1,2,2,R03,BMT,Astoria,Astoria Blvd,Q,N W,Elevated,40.770258,-73.917843
2,3,3,R04,BMT,Astoria,30 Av,Q,N W,Elevated,40.766779,-73.921479
3,4,4,R05,BMT,Astoria,Broadway,Q,N W,Elevated,40.761820,-73.925508
4,5,5,R06,BMT,Astoria,36 Av,Q,N W,Elevated,40.756804,-73.929575

## Package to get address
https://pypi.org/project/geopy/

In [3]:
from uszipcode import Zipcode
from uszipcode import SearchEngine
search = SearchEngine(simple_zipcode=True) 

from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="this is a test app")
zipcode = []
address = []
for index, row in mta_data.iterrows():
    # Search zipcode within 2 miles, ordered from closest to farthest
    tmp = search.by_coordinates(row['GTFS Latitude'], row['GTFS Longitude'], radius=2, returns=1)
    if tmp:
        zipcode.append(tmp[0].zipcode)
        
    # Search address based on lan&lon
    location = geolocator.reverse(f"{row['GTFS Latitude']}, {row['GTFS Longitude']}")
    if location.address:
        address.append(location.address)
        
mta_data['Zip Code'] = zipcode
mta_data['Address'] = address
                                  
pd.options.display.max_rows
pd.set_option('display.max_colwidth', -1)
from operator import methodcaller
new_add_list = list(map(methodcaller("split", ", "), mta_data["Address"]))

mta_data["Zip Code2"] = [elem[-2] for elem in new_add_list]
mta_data["Address2"] = [f"{elem[0]}, {elem[1]}" for elem in new_add_list]
                                  
# mta_data.to_csv("Resources/mta_with_zip.csv")
mta_data.head()

,Station ID,Complex ID,GTFS Stop ID,Division,Line,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,Zip Code,Address,Zip Code2,Address2
0,1,1,R01,BMT,Astoria,Astoria - Ditmars Blvd,Q,N W,Elevated,40.775036,-73.912034,11105,"Astoria-Ditmars Boulevard, 31st Street, Steinway, Queens County, NYC, New York, 11101, USA",11101,"Astoria-Ditmars Boulevard, 31st Street"
1,2,2,R03,BMT,Astoria,Astoria Blvd,Q,N W,Elevated,40.770258,-73.917843,11102,"Astoria Boulevard, Hoyt Avenue South, Astoria, Queens County, NYC, New York, NY 11106, USA",NY 11106,"Astoria Boulevard, Hoyt Avenue South"
2,3,3,R04,BMT,Astoria,30 Av,Q,N W,Elevated,40.766779,-73.921479,11102,"30th Avenue, 31st Street, Astoria, Queens County, NYC, New York, 11101, USA",11101,"30th Avenue, 31st Street"
3,4,4,R05,BMT,Astoria,Broadway,Q,N W,Elevated,40.761820,-73.925508,11102,"Broadway, 31st Street, Astoria, Queens County, NYC, New York, 11101, USA",11101,"Broadway, 31st Street"
4,5,5,R06,BMT,Astoria,36 Av,Q,N W,Elevated,40.756804,-73.929575,11106,"35-53, 31st Street, Sunnyside Gardens, Queens County, NYC, New York, 11106, USA",11106,"35-53, 31st Street"

In [4]:
mta_data.to_csv("Resources/mta_data_with_zip_address.csv")

# Zillow api

Over 1,000 calls in a day, API calls will be blocked

run up to 20 API calls on one page at one time

## GetDeepSearch-Results API
* http://www.zillow.com/webservice/GetDeepSearchResults.htm

Example:
Below is an example of calling the API for the address for the exact address match "2114 Bigelow Ave", "Seattle, WA":
http://www.zillow.com/webservice/GetDeepSearchResults.htm?zws-id=ZWSID&address=2114+Bigelow+Ave&citystatezip=Seattle%2C+WA

In [58]:
mta_data["Address3"] = [elem[0] for elem in new_add_list]
mta_data["Address4"] = [elem[1] for elem in new_add_list]
mta_data.head(100)

,Unnamed: 0,Station ID,Complex ID,GTFS Stop ID,Division,Line,Stop Name,Borough,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,Zip Code,Address,Zip Code2,Address2,Address3,Address4
0,0,1,1,R01,BMT,Astoria,Astoria - Ditmars Blvd,Q,N W,Elevated,40.775036,-73.912034,11105,"Astoria-Ditmars Boulevard, 31st Street, Steinway, Queens County, NYC, New York, 11101, USA",11101,"Astoria-Ditmars Boulevard, 31st Street",Astoria-Ditmars Boulevard,31st Street
1,1,2,2,R03,BMT,Astoria,Astoria Blvd,Q,N W,Elevated,40.770258,-73.917843,11102,"Astoria Boulevard, Hoyt Avenue South, Astoria, Queens County, NYC, New York, NY 11106, USA",NY 11106,"Astoria Boulevard, Hoyt Avenue South",Astoria Boulevard,Hoyt Avenue South
2,2,3,3,R04,BMT,Astoria,30 Av,Q,N W,Elevated,40.766779,-73.921479,11102,"30th Avenue, 31st Street, Astoria, Queens County, NYC, New York, 11101, USA",11101,"30th Avenue, 31st Street",30th Avenue,31st Street
3,3,4,4,R05,BMT,Astoria,Broadway,Q,N W,Elevated,40.761820,-73.925508,11102,"Broadway, 31st Street, Astoria, Queens County, NYC, New York, 11101, USA",11101,"Broadway, 31st Street",Broadway,31st Street
4,4,5,5,R06,BMT,Astoria,36 Av,Q,N W,Elevated,40.756804,-73.929575,11106,"35-53, 31st Street, Sunnyside Gardens, Queens County, NYC, New York, 11106, USA",11106,"35-53, 31st Street",35-53,31st Street
5,5,6,6,R08,BMT,Astoria,39 Av,Q,N W,Elevated,40.752882,-73.932755,11106,"38-34, 31st Street, Sunnyside, Queens County, NYC, New York, 11101, USA",11101,"38-34, 31st Street",38-34,31st Street
6,6,7,613,R11,BMT,Astoria,Lexington Av/59 St,M,N W R,Subway,40.762660,-73.967258,10065,"149, East 60th Street, Upper East Side, Lenox Hill, Manhattan, Manhattan Community Board 8, New York County, NYC, New York, 10065, USA",10065,"149, East 60th Street",149,East 60th Street
7,7,8,8,R13,BMT,Astoria,5 Av/59 St,M,N W R,Subway,40.764811,-73.973347,10153,"Grand Army Plaza, Upper East Side, Manhattan, New York County, NYC, New York, 10153, USA",10153,"Grand Army Plaza, Upper East Side",Grand Army Plaza,Upper East Side
8,8,9,9,R14,BMT,Broadway - Brighton,57 St - 7 Av,M,N Q R W,Subway,40.764664,-73.980658,10103,"Park Central Hotel, 860, 7th Avenue, Diamond District, Midtown, Manhattan, Manhattan Community Board 5, New York County, NYC, New York, 10019, USA",10019,"Park Central Hotel, 860",Park Central Hotel,860
9,9,10,10,R15,BMT,Broadway - Brighton,49 St,M,N R W,Subway,40.759901,-73.984139,10020,"721, 7th Avenue, Times Square, Manhattan, Manhattan Community Board 5, New York County, NYC, New York, 10019, USA",10019,"721, 7th Avenue",721,7th Avenue
10,10,11,611,R16,BMT,Broadway - Brighton,Times Sq - 42 St,M,N Q R W,Subway,40.754672,-73.986754,10110,"1440, Broadway, Times Square, Manhattan, Manhattan Community Board 5, New York County, NYC, New York, 10018, USA",10018,"1440, Broadway",1440,Broadway
11,11,12,607,R17,BMT,Broadway - Brighton,34 St - Herald Sq,M,N Q R W,Subway,40.749567,-73.987950,10001,"6th Avenue, Herald Square, Manhattan, Manhattan Community Board 5, New York County, NYC, New York, 10019, USA",10019,"6th Avenue, Herald Square",6th Avenue,Herald Square
12,12,13,13,R18,BMT,Broadway - Brighton,28 St,M,R W,Subway,40.745494,-73.988691,10001,"1180, Broadway, Korea Town, NoMad, Manhattan, Manhattan Community Board 5, New York County, NYC, New York, 10001, USA",10001,"1180, Broadway",1180,Broadway
13,13,14,14,R19,BMT,Broadway - Brighton,23 St,M,R W,Subway,40.741303,-73.989344,10011,"949, Broadway, Flatiron District, Manhattan, Manhattan Community Board 5, New York County, NYC, New York, 10010, USA",10010,"949, Broadway",949,Broadway
14,14,15,602,R20,BMT,Broadway - Brighton,14 St - Union Sq,M,N Q R W,Subway,40.735736,-73.990568,10003,"Union Square Dog Run, East 15th Street, Union Square, Manhattan, Manhattan Community Board 5, New York County, NYC, New York, 10003, USA",10003,"Union Square Dog Run, East 15th Street",Union Square Dog Run,East 15th Street
15,15,16,16,R21,BMT,Broadway - Brighton,8 St - NYU,M,R W,Subway,40.730328,-73.992629,10003,"755A, Broadway, NoHo Historic District, NoHo, Manhattan, Manhattan Community Board 2, New York County, NYC, New York, 10003, USA",10003,"755A, Broadway",755A,Broadway
16,16,17,17,R22,BMT,Broadway - Brighton,Prince St,M,R W,Subway,40.724329,-73.997702,10012,"La Mer 575 Broadway, 575, Broadway, SoHo, Manhattan, Manhattan Community Board 2, New York County, NYC, New York, 10012, USA",10012,"La Mer 575 Broadway, 575",La Mer 575 Broadway,575
17,17,18,623,R23,BMT,Broadway,Canal St,M,R W,Subway,40.719527,-74.001775,10278,"419B, Broadway, SoHo, Manhattan, Manhattan Community Board 2, New York County, NYC, New York, 10013, USA",10013,"419B, Broadway",419B,Broadway
18,18,19,623,Q01,BMT,Manhattan Bridge,Canal St,M,N Q,Subway,40.718383,-74.000460,10278,"247, Canal Street, Chinatown, Manhattan, Manhattan Community Board 2, New York County, NYC, New York, 10013, USA",10013,"247, Canal Street",247,Canal Street
19,19,20,20,R24,BMT,Broadway,City Hall,M,R W,Subway,40.713282,-74.006978,10007,"City Hall, Broadway, Civic Center, Manhattan, Manhattan Community Board 1, New York County, NYC, New York, 10003, USA",10003,"City Hall, Broadway",City Hall,Broadway
20,20,21,21,R25,BMT,Broadway,Cortlandt St,M,R W,Subway,40.710668,-74.011029,10271,"Cortlandt Street, Church Street, Financial District, Manhattan, Manhattan Community Board 1, New York County, NYC, New York, 10013, USA",10013,"Cortlandt Street, Church Street",Cortlandt Street,Church Street
21,21,22,22,R26,BMT,Broadway,Rector St,M,R W,Subway,40.707220,-74.013342,10006,"Rector Street, Trinity Place, Financial District, Manhattan, Manhattan Community Board 1, New York County, NYC, New York, 10006, USA",10006,"Rector Street, Trinity Place",Rector Street,Trinity Place
22,22,23,635,R27,BMT,Broadway,Whitehall St,M,R W,Subway,40.703087,-74.012994,10006,"3 New York Plaza, 39, Whitehall Street, Financial District, Manhattan, Manhattan Community Board 1, New York County, NYC, New York, 10004, USA",10004,"3 New York Plaza, 39",3 New York Plaza,39
23,23,24,620,R28,BMT,Broadway,Court St,Bk,R,Subway,40.694100,-73.991777,11201,"Court Street, Montague Street, Brooklyn Heights, Kings County, NYC, New York, 11201, USA",11201,"Court Street, Montague Street",Court Street,Montague Street
24,24,25,636,R29,BMT,Broadway,Jay St - MetroTech,Bk,R,Subway,40.692180,-73.985942,11201,"81, Willoughby Street, Downtown Brooklyn, Kings County, NYC, New York, 11201, USA",11201,"81, Willoughby Street",81,Willoughby Street
25,25,26,26,R30,BMT,Broadway - Brighton,DeKalb Av,Bk,B Q R,Subway,40.690635,-73.981824,11217,"33, Flatbush Avenue Extension, Downtown Brooklyn, Kings County, NYC, New York, 11201, USA",11201,"33, Flatbush Avenue Extension",33,Flatbush Avenue Extension
26,26,27,617,R31,BMT,4th Av,Atlantic Av - Barclays Ctr,Bk,D N R,Subway,40.683666,-73.978810,11217,"BluePearl Specialty + Emergency Pet Hospital, 34, 4th Avenue, Gowanus, BK, Kings County, NYC, New York, 11217, USA",11217,"BluePearl Specialty + Emergency Pet Hospital, 34",BluePearl Specialty + Emergency Pet Hospital,34
27,27,28,28,R32,BMT,4th Av,Union St,Bk,R,Subway,40.677316,-73.983110,11217,"Union Street, 4th Avenue, Park Slope, BK, Kings County, NYC, New York, 11209, USA",11209,"Union Street, 4th Avenue",Union Street,4th Avenue
28,28,29,608,R33,BMT,4th Av,9 St,Bk,R,Subway,40.670847,-73.988302,11215,"P.S. 118 The Maurice Sendak Community School, 4th Avenue, Park Slope, BK, Kings County, NYC, New York, 11209, USA",11209,"P.S. 118 The Maurice Sendak Community School, 4th Avenue",P.S. 118 The Maurice Sendak Community School,4th Avenue
29,29,30,30,R34,BMT,4th Av,Prospect Av,Bk,R,Subway,40.665414,-73.992872,11215,"Prospect Expressway, Park Slope, BK, Kings County, NYC, New York, 11215, USA",11215,"Prospect Expressway, Park Slope",Prospect Expressway,Park Slope
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,70,71,71,N02,BMT,Sea Beach,8 Av,Bk,N,Open Cut,40.635064,-74.011719,11220,"740, 61st Street, Dyker Heights, Kings County, NYC, New York, 11220, USA",11220,"740, 61st Street",740,61st Street
71,71,72,72,N03,BMT,Sea Beach,Fort Hamilton Pkwy,Bk,N,Open Cut,40.631386,-74.005351,11219,"1042, 62nd Street, Dyker Heights, Kings County, NYC, New York, 11219, USA",11219,"1042, 62nd Street",1042,62nd Street
72,72,73,615,N04,BMT,Sea Beach,New Utrecht Av,Bk,N,Open Cut,40.624842,-73.996353,11219,"1462, 62nd Street, Borough Park, Kings County, NYC, New York, 11219, USA",11219,"1462, 62nd Street",1462,62nd Street
73,73,74,74,N05,BMT,Sea Beach,18 Av,Bk,N,Open Cut,40.620671,-73.990414,11204,"1744, 63rd Street, Borough Park, BK, Kings County, NYC, New York, 11204, USA",11204,"1744, 63rd Street",1744,63rd Street
74,74,75,75,N06,BMT,Sea Beach,20 Av,Bk,N,Open Cut,40.617410,-73.985026,11204,"6310, 20th Avenue, New Utrecht, BK, Kings County, NYC, New York, 11204, USA",11204,"6310, 20th Avenue",6310,20th Avenue
75,75,76,76,N07,BMT,Sea Beach,Bay Pkwy,Bk,N,Open Cut,40.611815,-73.981848,11204,"1370, West 7th Street, Gravesend, BK, Kings County, NYC, New York, 11204, USA",11204,"1370, West 7th Street",1370,West 7th Street
76,76,77,77,N08,BMT,Sea Beach,Kings Hwy,Bk,N,Open Cut,40.603923,-73.980353,11223,"1778, West 7th Street, Gravesend, BK, Kings County, NYC, New York, 11223, USA",11223,"1778, West 7th Street",1778,West 7th Street
77,77,78,78,N09,BMT,Sea Beach,Avenue U,Bk,N,Open Cut,40.597473,-73.979137,11223,"2044, West 7th Street, Gravesend, BK, Kings County, NYC, New York, 11223, USA",11223,"2044, West 7th Street",2044,West 7th Street
78,78,79,79,N10,BMT,Sea Beach,86 St,Bk,N,Open Cut,40.592721,-73.978230,11223,"86th Street, 86 St, Gravesend, Kings County, NYC, New York, 11223, USA",11223,"86th Street, 86 St",86th Street,86 St
79,79,80,80,J12,BMT,Jamaica,121 St,Q,J Z,Elevated,40.700492,-73.828294,11418,"121st Street, Jamaica Avenue, Richmond Hill, Queens County, NYC, New York, 11418, USA",11418,"121st Street, Jamaica Avenue",121st Street,Jamaica Avenue
80,80,81,81,J13,BMT,Jamaica,111 St,Q,J,Elevated,40.697418,-73.836345,11418,"112-02, Jamaica Avenue, Brooklyn Manor, Queens County, NYC, New York, 11418, USA",11418,"112-02, Jamaica Avenue",112-02,Jamaica Avenue
81,81,82,82,J14,BMT,Jamaica,104 St,Q,J Z,Elevated,40.695178,-73.844330,11416,"104th Street, Jamaica Avenue, Brooklyn Manor, Queens County, NYC, New York, 11418, USA",11418,"104th Street, Jamaica Avenue",104th Street,Jamaica Avenue
82,82,83,83,J15,BMT,Jamaica,Woodhaven Blvd,Q,J Z,Elevated,40.693879,-73.851576,11416,"Woodhaven Boulevard, Jamaica Avenue, Brooklyn Manor, Queens County, NYC, New York, 11421, USA",11421,"Woodhaven Boulevard, Jamaica Avenue",Woodhaven Boulevard,Jamaica Avenue
83,83,84,84,J16,BMT,Jamaica,85 St - Forest Pkwy,Q,J,Elevated,40.692435,-73.860010,11421,"85th Street–Forest Parkway, Jamaica Avenue, Brooklyn Manor, Queens County, NYC, New York, 11421, USA",11421,"85th Street–Forest Parkway, Jamaica Avenue",85th Street–Forest Parkway,Jamaica Avenue
84,84,85,85,J17,BMT,Jamaica,75 St,Q,J Z,Elevated,40.691324,-73.867139,11421,"74-24, Jamaica Avenue, Brooklyn Manor, Queens County, NYC, New York, 11421, USA",11421,"74-24, Jamaica Avenue",74-24,Jamaica Avenue
85,85,86,86,J19,BMT,Jamaica,Cypress Hills,Bk,J,Elevated,40.689941,-73.872550,11421,"876, Jamaica Avenue, Brooklyn Manor, Queens County, NYC, New York, 11208, USA",11208,"876, Jamaica Avenue",876,Jamaica Avenue
86,86,87,87,J20,BMT,Jamaica,Crescent St,Bk,J Z,Elevated,40.683194,-73.873785,11421,"3289, Fulton Street, City Line, Kings County, NYC, New York, 11208, USA",11208,"3289, Fulton Street",3289,Fulton Street
87,87,88,88,J21,BMT,Jamaica,Norwood Av,Bk,J Z,Elevated,40.681410,-73.880039,11208,"3118, Fulton Street, Cypress Hills, Kings County, NYC, New York, 11208, USA",11208,"3118, Fulton Street",3118,Fulton Street
88,88,89,89,J22,BMT,Jamaica,Cleveland St,Bk,J,Elevated,40.679947,-73.884639,11208,"2986, Fulton Street, Cypress Hills, Kings County, NYC, New York, 11208, USA",11208,"2986, Fulton Street",2986,Fulton Street
89,89,90,90,J23,BMT,Jamaica,Van Siclen Av,Bk,J Z,Elevated,40.678024,-73.891688,11207,"2788, Fulton Street, Cypress Hills, Kings County, NYC, New York, 11207, USA",11207,"2788, Fulton Street",2788,Fulton Street
90,90,91,91,J24,BMT,Jamaica,Alabama Av,Bk,J,Elevated,40.676992,-73.898654,11207,"BP, Fulton Street, Broadway Junction, Kings County, NYC, New York, 11208, USA",11208,"BP, Fulton Street",BP,Fulton Street
91,91,92,621,J27,BMT,Jamaica,Broadway Jct,Bk,J Z,Elevated,40.679498,-73.904512,11207,"1945, Broadway, Broadway Junction, Kings County, NYC, New York, 11207, USA",11207,"1945, Broadway",1945,Broadway
92,92,93,93,J28,BMT,Jamaica,Chauncey St,Bk,J Z,Elevated,40.682893,-73.910456,11233,"Chauncey Street, Broadway, Ocean Hill, Kings County, NYC, New York, 11207, USA",11207,"Chauncey Street, Broadway",Chauncey Street,Broadway
93,93,94,94,J29,BMT,Jamaica,Halsey St,Bk,J,Elevated,40.686370,-73.916559,11233,"Halsey Street, Broadway, Bushwick, BK, Kings County, NYC, New York, 11207, USA",11207,"Halsey Street, Broadway",Halsey Street,Broadway
94,94,95,95,J30,BMT,Jamaica,Gates Av,Bk,J Z,Elevated,40.689630,-73.922270,11221,"Gates Avenue, Broadway, Bushwick, BK, Kings County, NYC, New York, 11207, USA",11207,"Gates Avenue, Broadway",Gates Avenue,Broadway
95,95,96,96,J31,BMT,Jamaica,Kosciuszko St,Bk,J,Elevated,40.693342,-73.928814,11221,"Kosciuszko Street, Broadway, Bushwick, BK, Kings County, NYC, New York, 11207, USA",11207,"Kosciuszko Street, Broadway",Kosciuszko Street,Broadway
96,96,97,97,M11,BMT,Jamaica,Myrtle Av,Bk,J M Z,Elevated,40.697207,-73.935657,11206,"Myrtle Avenue, Broadway, Bushwick, BK, Kings County, NYC, New York, 11207, USA",11207,"Myrtle Avenue, Broadway",Myrtle Avenue,Broadway
97,97,98,98,M12,BMT,Jamaica,Flushing Av,Bk,J M,Elevated,40.700260,-73.941126,11206,"773, Broadway, Bed-Stuy, Kings County, NYC, New York, 11206, USA",11206,"773, Broadway",773,Broadway
98,98,99,99,M13,BMT,Jamaica,Lorimer St,Bk,J M,Elevated,40.703869,-73.947408,11211,"Lorimer Street, Broadway, Williamsburg, Kings County, NYC, New York, 11207, USA",11207,"Lorimer Street, Broadway",Lorimer Street,Broadway
99,99,100,100,M14,BMT,Jamaica,Hewes St,Bk,J M,Elevated,40.706870,-73.953431,11211,"418, Broadway, Williamsburg, Kings County, NYC, New York, 11211, USA",11211,"418, Broadway",418,Broadway

In [74]:
from xmljson import badgerfish as bf
import json
from json import dumps

zillow_url = "http://www.zillow.com/webservice/GetDeepSearchResults.htm"
params = { 'zws-id': z_key }
results_fetch_key = "{http://www.zillow.com/static/xsd/SearchResults.xsd}searchresults"

zpid = []
latitude = []
longitude = []
bathrooms = []
bedrooms = []
zipcode = []
price = []
lotSizeSqFt = []
usecode = []
for index, row in mta_data.iterrows():
    params['address'] = row['Stop Name']
    params['citystatezip'] = row['Zip Code2']
    
    response = requests.get(zillow_url, params=params)
    
    json_data = bf.data(fromstring(response.content))    
    if json_data[results_fetch_key]["message"]["code"]["$"] == 0:
        results = json_data[results_fetch_key]['response']['results']['result']
        if not isinstance(results, list):
            results = [results]
            
        for house in results:
            zpid.append(house['zpid']['$'])
            latitude.append(house['address']['latitude']['$'])
            longitude.append(house['address']['longitude']['$'])
            usecode.append(house['useCode']['$'])
            
            if 'zipcode' in house['address'] and '$' in house['address']['zipcode']:
                zipcode.append(house['address']['zipcode']['$'])
            else:
                zipcode.append(0)
            
            if 'bathrooms' in house:
                bathrooms.append(house['bathrooms']['$'])
            else:
                bathrooms.append(0)

            if 'bedrooms' in house:
                bedrooms.append(house['bedrooms']['$'])
            else:
                bedrooms.append(0)

            if 'amount' in house['zestimate'] and '$' in house['zestimate']['amount']:
                price.append(house['zestimate']['amount']['$'])
            else:
                price.append(0)

            if 'lotSizeSqFt' in house:
                lotSizeSqFt.append(house['lotSizeSqFt']['$'])
            else:
                lotSizeSqFt.append(0)           
                    
#     print(dumps(json_data, indent=4, sort_keys=True) )
#     break
    
df = pd.DataFrame(columns=['zpid'])
df['zpid'] = zpid
df['latitude'] = latitude
df['longitude'] = longitude
df['usecode'] = usecode
df['bathrooms'] = bathrooms
df['bedrooms'] = bedrooms
df['zipcode'] = zipcode
df['price'] = price
df['lotSizeSqFt'] = lotSizeSqFt
df.head()

,zpid,latitude,longitude,usecode,bathrooms,bedrooms,zipcode,price,lotSizeSqFt
0,31947881,40.780026,-73.916672,SingleFamily,1.0,3,11105,1297999,2500
1,94721483,40.770830,-73.903180,MultiFamily2To4,1.0,2,11105,687975,0
2,2095007549,40.769199,-73.901496,MultiFamily2To4,4.0,5,11105,1141827,0
3,2099075333,40.779510,-73.915470,MultiFamily2To4,2.0,5,11105,1177104,2500
4,2086385859,40.781942,-73.918467,MultiFamily2To4,1.0,2,11105,593844,0

In [75]:
df.to_csv("Resources/Mar_3rd_stopname_zipcode2_df.csv")
df.shape

(5574, 9)

In [8]:
df = pd.read_csv("Resources/sample_df.csv")

# Combine all house info file

In [142]:
sn_zp = pd.read_csv("Resources/Mar_3rd_stopname_zipcode_df.csv")
ad2_zp = pd.read_csv("Resources/Mar_3rd_address2_zipcode_df.csv")
ad3_zp = pd.read_csv("Resources/Mar_3rd_address3_zipcode_df.csv")
ad4_zp = pd.read_csv("Resources/Mar_3rd_address4_zipcode_df.csv")
sn_zp2 = pd.read_csv("Resources/Mar_3rd_stopname_zipcode2_df.csv")
ad2_zp2 = pd.read_csv("Resources/Mar_3rd_address2_zipcode2_df.csv")
ad3_zp2 = pd.read_csv("Resources/Mar_3rd_address3_zipcode2_df.csv")
ad4_zp2 = pd.read_csv("Resources/Mar_3rd_address4_zipcode2_df.csv")

In [143]:
print(sn_zp.shape)
print(ad2_zp.shape)
print(ad3_zp.shape)
print(ad4_zp.shape)
print(sn_zp2.shape)
print(ad2_zp2.shape)
print(ad3_zp2.shape)
print(ad4_zp2.shape)

(5208, 10)
(989, 10)
(4026, 10)
(6187, 10)
(5574, 10)
(849, 10)
(3916, 10)
(6238, 10)

In [184]:
combo_df = sn_zp
combo_df = combo_df.append(ad2_zp, sort=False)
combo_df = combo_df.append(ad3_zp, sort=False)
combo_df = combo_df.append(ad4_zp, sort=False)
combo_df = combo_df.append(sn_zp2, sort=False)
combo_df = combo_df.append(ad2_zp2, sort=False)
combo_df = combo_df.append(ad3_zp2, sort=False)
combo_df = combo_df.append(ad4_zp2, sort=False)
combo_df.shape

(32987, 10)

In [185]:
unique_df = combo_df.drop_duplicates(subset='zpid')
unique_df.shape

(15282, 10)

In [186]:
unique_df = unique_df.reset_index().drop(['index', 'Unnamed: 0'], axis=1)
unique_df.head()

,zpid,latitude,longitude,usecode,bathrooms,bedrooms,zipcode,price,lotSizeSqFt
0,31947881,40.780026,-73.916672,SingleFamily,1.0,3,11105,1297999,2500
1,94721614,40.770830,-73.903180,MultiFamily2To4,1.0,1,11105,543865,0
2,31947885,40.779837,-73.916406,SingleFamily,1.0,3,11105,1402414,2500
3,31943243,40.768852,-73.900892,Triplex,0.0,0,11105,1290066,2200
4,31943244,40.768754,-73.900791,Duplex,0.0,0,11105,1150027,2180

In [187]:
unique_df['zpid'].nunique()

15282

In [188]:
unique_df = unique_df[unique_df['price'] != 0]
print(unique_df.shape)
unique_df.to_csv("Resources/Combine_home_data.csv")

(11469, 9)

In [189]:
unique_df.head()

,zpid,latitude,longitude,usecode,bathrooms,bedrooms,zipcode,price,lotSizeSqFt
0,31947881,40.780026,-73.916672,SingleFamily,1.0,3,11105,1297999,2500
1,94721614,40.770830,-73.903180,MultiFamily2To4,1.0,1,11105,543865,0
2,31947885,40.779837,-73.916406,SingleFamily,1.0,3,11105,1402414,2500
3,31943243,40.768852,-73.900892,Triplex,0.0,0,11105,1290066,2200
4,31943244,40.768754,-73.900791,Duplex,0.0,0,11105,1150027,2180

In [190]:
unique_df['usecode'].unique()

array(['SingleFamily', 'MultiFamily2To4', 'Triplex', 'Duplex',
       'Condominium', 'Quadruplex', 'Unknown', 'Townhouse', 'Apartment',
       'Cooperative', 'Mobile', 'Miscellaneous', 'VacantResidentialLand',
       'MultiFamily5Plus'], dtype=object)

### Calculate neareat Station

In [194]:
from scipy.spatial import distance
mat = distance.cdist(
        unique_df[['latitude', 'longitude']],
        mta_data[['GTFS Latitude', 'GTFS Longitude']],
        metric = 'euclidean')
distance_df = pd.DataFrame(mat, index=unique_df['zpid'], columns=mta_data['Station ID'])

arr = distance_df.values
unique_df['Nearest Station Index']  = [list(i).index(i.min()) for i in arr]
unique_df['Nearest Station Lat'] = [mta_data.loc[i, 'GTFS Latitude'] for i in unique_df['Nearest Station Index']]
unique_df['Nearest Station Lon'] = [mta_data.loc[i, 'GTFS Longitude'] for i in unique_df['Nearest Station Index']]

from math import sin, cos, sqrt, atan2, radians

def convert_latlon(row):
    R = 6373.0
    
    stoplat = radians(row['Nearest Station Lat'])
    stoplon = radians(row['Nearest Station Lon'])
    
    homelat = radians(row['latitude'])
    homelon = radians(row['longitude'])
    
    dlon = homelon - stoplon
    dlat = homelat - stoplat
    
    a = sin(dlat / 2)**2 + cos(stoplat) * cos(homelat) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    
    distance_km = R * c
    distance_m = distance_km * 0.621371
    
    return distance_m

unique_df['distance_miles'] = unique_df.apply(convert_latlon, axis=1)

In [196]:
unique_df.to_csv("Resources/final_house_data_with_nearest_station.csv")

In [197]:
unique_df.head()

,zpid,latitude,longitude,usecode,bathrooms,bedrooms,zipcode,price,lotSizeSqFt,Nearest Station Index,Nearest Station Lat,Nearest Station Lon,distance_miles
0,31947881,40.780026,-73.916672,SingleFamily,1.0,3,11105,1297999,2500,0,40.775036,-73.912034,0.421744
1,94721614,40.770830,-73.903180,MultiFamily2To4,1.0,1,11105,543865,0,0,40.775036,-73.912034,0.547056
2,31947885,40.779837,-73.916406,SingleFamily,1.0,3,11105,1402414,2500,0,40.775036,-73.912034,0.403068
3,31943243,40.768852,-73.900892,Triplex,0.0,0,11105,1290066,2200,0,40.775036,-73.912034,0.723042
4,31943244,40.768754,-73.900791,Duplex,0.0,0,11105,1150027,2180,0,40.775036,-73.912034,0.731314

### Google location api feed

In [122]:
import gmaps

# Google developer API key
from config import gkey

# Access maps with unique API key
gmaps.configure(api_key=gkey)

In [123]:
unique_df.head()

,zpid,latitude,longitude,usecode,bathrooms,bedrooms,zipcode,price,lotSizeSqFt
0,31947881,40.780026,-73.916672,SingleFamily,1.0,3,11105,1297999,2500
1,94721614,40.770830,-73.903180,MultiFamily2To4,1.0,1,11105,543865,0
2,31947885,40.779837,-73.916406,SingleFamily,1.0,3,11105,1402414,2500
3,31943243,40.768852,-73.900892,Triplex,0.0,0,11105,1290066,2200
4,31943244,40.768754,-73.900791,Duplex,0.0,0,11105,1150027,2180

In [141]:
# Store latitude and longitude in locations
locations = unique_df[["latitude", "longitude"]]

# Fill NaN values and convert to float
price = unique_df["price"].astype(float)

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=price, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=0.001)

# Add layer
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))